name: Bug Report
description: Create a report to help us improve
title: "Bug: "
assignees: D4rk-S0ul
type: Bug

body:

    # Description
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the Bug
      description: Please enter a clear and concise description description of the bug.

    # Steps to Reproduce
  - type: textarea
    validations:
      required: true
    attributes:
      label: Steps to Reproduce
      description: Please provide any required setup and steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error

    # Expected Behavior
  - type: textarea
    attributes:
      label: Expected Behavior
      description: Please provide a description of what you expected to happen.

    # Screenshots
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots here to help explain your problem.

    # FlashCards Version
  - type: input
    validations:
      required: true
    attributes:
      label: FlashCards Version
      description: Which version of FlashCards are you using? To see your FlashCards version, open the FlashCards App and access it from Settings -> About -> FlashCards - Version.
      placeholder: "e.g. 1.0.3"

  # Windows Build
  - type: input
    validations:
      required: true
    attributes:
      label: Windows Build
      description: Which version of Windows are you using? To see your Windows version, open the Windows Settings and access it from System -> About -> Windows specifications -> OS build.
      placeholder: "e.g. 22631.4169"

    # Additional Context
  - type: textarea
    attributes:
      label: Additional Context
      description: Please enter any other applicable info here.
